include:
  - local: .gitlab/templates/calculate-version.yml
  - local: .gitlab/templates/test-service.yml
  - local: .gitlab/templates/build-service.yml
  - local: .gitlab/templates/docker-build-ecr.yml
  - local: .gitlab/templates/terraform-base.yml
  - local: .gitlab/templates/create-release.yml

variables:
  SERVICES: lambda,todo-app

workflow:
  rules:
    # only run if the pipeline is triggered by a merge request or the branch is the default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - build
  - docker
  - deploy
  - release
  - tear-down

# Use the version calculation template
calculate-version:
  stage: .pre
  extends: .calculate-version

test-eventpro-api:
  extends: .test-service
  stage: test

gradle-build-eventpro-api:
  extends: .build-service
  stage: build

npm-build-web:
  stage: build
  image: node:20
  script:
    - cd web
    - npm install
    - npm run build
  artifacts:
    paths:
      - web/dist
    expire_in: 1 hour

docker-build-secret-rotation-lambda:
  extends: .build-service-docker-image  
  variables:
    SERVICES_DIR: secret-rotation
    DOCKERFILE_PATH: Dockerfile
    ECR_REPOSITORY_IMAGE: $ECR_REGISTRY/todo-db-rotation-lambda
    VERSION: $VERSION

docker-build-eventpro-api:
  extends: .build-service-docker-image
  variables:
    SERVICES_DIR: eventpro-api
    DOCKERFILE_PATH: Dockerfile
    ECR_REPOSITORY_IMAGE: $ECR_REGISTRY/access-eventpro-api
    VERSION: $VERSION

terraform-deploy-eventpro:
  extends: .terraform-base
  stage: deploy
  needs:
    - job: calculate-version
      artifacts: true
    - job: docker-build-secret-rotation-lambda
    - job: docker-build-eventpro-api
  script:
    - |
      terraform apply --auto-approve \
        -var="eventpro-api_image=$ECR_REGISTRY/access-eventpro-api:$VERSION" \
        -var="secret-rotation_lambda_image=$ECR_REGISTRY/access-secret-rotation:$VERSION" 
    # Extract ALB URL for GitLab Environment
    - echo "ALB_URL=$(terraform output -raw alb_url)" >> deploy.env
    - echo "Application Load Balancer URL is $(terraform output -raw alb_url)"
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: production
    url: $ALB_URL
  when: manual

serve-web-static-files:
  stage: build
  image: node:20
  script:
    - cd web
    - npm install
    - npm run build
  artifacts:
    paths:
      - web/dist

create-release:
  extends: .create-release
  stage: release
  needs:
    - job: calculate-version
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

terraform-destroy-eventpro:
  extends: .terraform-base
  stage: tear-down
  script:
    - |
      terraform destroy --auto-approve \
        -var="eventpro-api_image=$ECR_REGISTRY/access-eventpro-api:$VERSION" \
        -var="secret-rotation_lambda_image=$ECR_REGISTRY/access-secret-rotation:$VERSION" 
  when: manual
