include:
  - local: .gitlab/templates/calculate-version.yml
  - local: .gitlab/templates/test-service.yml
  - local: .gitlab/templates/test-web.yml
  - local: .gitlab/templates/build-backend.yml
  - local: .gitlab/templates/docker-build-ecr.yml
  - local: .gitlab/templates/terraform-base.yml
  - local: .gitlab/templates/create-release.yml

workflow:
  rules:
    # only run if the pipeline is triggered by a merge request or the branch is the default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - build
  - docker
  - deploy
  - post-deploy
  - release
  - tear-down

# Use the version calculation template
calculate-version:
  stage: .pre
  extends: .calculate-version

test-backend:
  extends: .test-service
  stage: test
  needs:
    - job: calculate-version
      artifacts: true

test-web:
  extends: .test-web
  stage: test
  needs:
    - job: calculate-version
      artifacts: true

gradle-build-backend:
  extends: .build-backend
  stage: build
  needs:
    - job: calculate-version
      artifacts: true
    - job: test-backend

npm-build-frontend:
  stage: build
  image: node:22-alpine
  before_script:
    - cd frontend
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
  needs:
    - job: calculate-version
      artifacts: true
    - job: test-web

docker-build-secret-rotation-lambda:
  extends: .docker-build-ecr  
  needs:
    - job: calculate-version
      artifacts: true
    - job: gradle-build-backend
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker image build -t $ECR_REGISTRY/eventpro-secret-rotation:$VERSION ./secret-rotation
    - docker image push $ECR_REGISTRY/eventpro-secret-rotation:$VERSION

docker-build-backend:
  extends: .docker-build-ecr
  needs:
    - job: calculate-version
      artifacts: true
    - job: gradle-build-backend
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker image build -t $ECR_REGISTRY/eventpro-backend:$VERSION ./backend
    - docker image push $ECR_REGISTRY/eventpro-backend:$VERSION

terraform-deploy-eventpro:
  extends: .terraform-base
  stage: deploy
  needs:
    - job: calculate-version
      artifacts: true
    - job: docker-build-secret-rotation-lambda
    - job: docker-build-backend
  script:
    - |
      terraform apply --auto-approve \
        -var="backend_image=$ECR_REGISTRY/eventpro-backend:$VERSION" \
        -var="secret-rotation_lambda_image=$ECR_REGISTRY/eventpro-secret-rotation:$VERSION" 
    # Extract ALB URL for GitLab Environment
    - echo "ALB_URL=https://$(terraform output -raw alb_dns_name)" >> deploy.env
    - echo "Application Load Balancer URL is https://$(terraform output -raw alb_dns_name)"
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: production
    url: $ALB_URL
  when: manual

serve-frontend-static-files:
  stage: post-deploy
  image: amazon/aws-cli:2.23.0
  needs: 
    - job: terraform-deploy-eventpro
    - job: npm-build-frontend
      artifacts: true
  before_script:
    - cd infrastructure/environments/dev
  script:
    - S3_BUCKET=$(terraform output -raw frontend_bucket_name)
    - echo "Uploading frontend static files to $S3_BUCKET"
    - aws s3 sync ../../../frontend/dist/ s3://$S3_BUCKET/ --delete
    - echo "Frontend static files uploaded to s3://$S3_BUCKET"

create-release:
  extends: .create-release
  stage: release
  needs:
    - job: calculate-version
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

terraform-destroy-eventpro:
  extends: .terraform-base
  stage: tear-down
  needs:
    - job: calculate-version
      artifacts: true
  script:
    - |
      terraform destroy --auto-approve \
        -var="backend_image=$ECR_REGISTRY/eventpro-backend:$VERSION" \
        -var="secret-rotation_lambda_image=$ECR_REGISTRY/eventpro-secret-rotation:$VERSION" 
  when: manual
