rootProject.name = 'backend'

// Modular Monolith Modules
include 'eventpro-core'
include 'eventpro-event'
include 'eventpro-order'
include 'eventpro-payment'
include 'eventpro-notification'
include 'eventpro-api'

project(':eventpro-core').projectDir = file('modules/eventpro-core')
project(':eventpro-event').projectDir = file('modules/eventpro-event')
project(':eventpro-order').projectDir = file('modules/eventpro-order')
project(':eventpro-payment').projectDir = file('modules/eventpro-payment')
project(':eventpro-notification').projectDir = file('modules/eventpro-notification')
project(':eventpro-api').projectDir = file('modules/eventpro-api')

