rootProject.name = 'services'

include 'services:core-api'
include 'services:event-api'
include 'services:lambdas:order-processor'
include 'services:lambdas:payment-processor'
include 'services:lambdas:notification-sender'
include 'services:lambdas:analytics-service'
include 'shared:common'
include 'shared:messaging'
include 'shared:database'