plugins {
    id 'java'
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    
    // AWS SDK
    implementation platform("software.amazon.awssdk:bom:${project.ext.awsSdkVersion}")
    implementation 'software.amazon.awssdk:ses'
    implementation 'software.amazon.awssdk:sns'
    
    // Lombok
    compileOnly "org.projectlombok:lombok:${project.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${project.ext.lombokVersion}"
    
    // Module dependencies
    implementation project(':eventpro-core')
    
    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

