name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      services: ${{ steps.filter.outputs.services }}
      order-processor: ${{ steps.filter.outputs.order-processor }}
      payment-processor: ${{ steps.filter.outputs.payment-processor }}
      notification-sender: ${{ steps.filter.outputs.notification-sender }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'eventpro-frontend/**'
            services:
              - 'backend/services/**'
            order-processor:
              - 'backend/lambdas/order-processor/**'
            payment-processor:
              - 'backend/lambdas/payment-processor/**'
            notification-sender:
              - 'backend/lambdas/notification-sender/**'
