name: Frontend

on:
  workflow_call:
    inputs:
      api-base-url:
        description: 'API Base URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: deploy
        uses: ./.github/actions/terraform
        with:
          working-directory: eventpro-frontend/terraform

    #   - name: upload-to-s3
        