name: API

on:
  push:
    branches:
      - main
    tags:
      - 'api-v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to deploy to'
        required: true
        default: 'dev'
        type: string
  workflow_call:
    inputs:
      workspace:
        description: 'Workspace to deploy to'
        required: true
        default: 'dev'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/gradle-task
        with:
          working-directory: backend/services
          java-version: '25'

      - name: Resolve image tags
        id: image-meta
        uses: ./.github/actions/image-tags
        with:
          tag-prefix: api-v

      - name: ecr-docker-build
        id: ecr-docker-build
        uses: ./.github/actions/docker
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          ecr-repository: eventpro-api
          context: backend/services
          dockerfile: Dockerfile
          image-tag: ${{ steps.image-meta.outputs.primary_tag }}
          image-tags: ${{ steps.image-meta.outputs.all_tags }}

      - name: deploy
        uses: ./.github/actions/terraform
        with:
          working-directory: backend/services/terraform
          workspace: ${{ inputs.workspace }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          variables: image_registry=${{ steps.ecr-docker-build.outputs.image-registry }},image_name=${{ steps.ecr-docker-build.outputs.image-name }},image_tag=${{ steps.ecr-docker-build.outputs.image-tag }},domain_name=${{ vars.DOMAIN_NAME }},alb_certificate_arn=${{ vars.ACM_CERTIFICATE_ARN }},cloudfront_certificate_arn=${{ vars.ACM_CERTIFICATE_ARN }}
